package sm.dao;

import java.util.List;

import sm.pojo.NoveOrders;

public interface NoveOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orders
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orders
     *
     * @mbggenerated
     */
    int insert(NoveOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orders
     *
     * @mbggenerated
     */
    int insertSelective(NoveOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orders
     *
     * @mbggenerated
     */
    NoveOrders selectByPrimaryKey(String orderId);
    List<NoveOrders> selectByUserId(Integer orderId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoveOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoveOrders record);
}